openapi: 3.0.1
info:
  title: AVI Standards of Veterinary Interoperabiity
  description: |
    ## This is a description of the project. Like all OAS description fields it can contain HTML    equation<br><br> ((1 - E^((offset - t)/ramp)/2)*scale)/E^(decay X t)
  termsOfService: link to a terms-of-service page
  contact:
    name: Site Maintainer
    email: standards@AVI.ORG
  version: 0.1.1
servers:
  - description: this would be a server set up as a reference implementation
    url: https://doesn'tExist@AVI.ORG

paths:
  /getCase:
    post:
      operationId: fit_single
      summary: Fit single lactation
      description: >-
        Fit a single lactation from the supplied array of  (DIM, milk weight) data pairs
        using a default tree of Bayesian priors stratified by on breed and parity.
      parameters:
        - name: includePath
          in: path
          schema:
            type: boolean
            default: false
      requestBody:
        description: a single lactation
        content:
          application/json:
            schema:
              required:
                - lactation
              properties:
                lactation:
                  $ref: "#/components/schemas/Lactation"
                priors:
                  $ref: "#/components/schemas/Priors"
        required: true
      responses:
        "200":
          description: Lactation fitted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Fit"
        '401':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Unauthorized'

    post:
      operationId: fit_lactations
      summary: Fit a list of lactations.
      description: >-
        Fit a group of lactations returning fitted parameter values. If '**_priors_**'
        are supplied they will be used. Otherwise fitting will be done from defaults.
      requestBody:
        content:
          application/json:
            schema:
              required:
                - fittingJob
              properties:
                fittingJob:
                  $ref: "#/components/schemas/FittingJob"
        required: true
      responses:
        "200":
          description: fitted parameter values for lactations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FittingResult"
        '401':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Unauthorized'
  /getCase/{sourceId}/{caseId}:
    get:
      operationId: getSingeleCase
      summary: Get Case data from a source by caseId 
      description: >-
        Get the default Priors that will be used if an alternative is not supplied by the user
      parameters:
        - name: sourceId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Case Data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Case"
        '401':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Unauthorized'
components:
  responses:
    Unauthorized:
      description: User lacks a required permission
    BadRequest:
      description: The server could not understand the request due to invalid syntax.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: The server can not find the requested resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Patient:
      required:
        - caseId
      type: object

      properties:
        caseId: 
          type: string
          format: uuid
          description: ID of patient
          example:  kergjq0o49gnqwi4t564jh489j
        name:
          type: string
          description: Name of patient
          default: ""
          example: Fluffy
      description: Patient answers to this name.
